# Generated by Django 2.2.7 on 2020-05-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_helper',
            field=models.BooleanField(default=False),
        ),
    ]
