# Generated by Django 2.2.7 on 2020-05-07 20:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200507_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '9999999999'. 10 digits.", regex='^[789]\\d{9}$')], verbose_name='phone'),
        ),
    ]
