# Generated by Django 2.2.7 on 2020-05-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200508_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lattitude',
            field=models.DecimalField(decimal_places=3, default=71.217, max_digits=8),
        ),
        migrations.AlterField(
            model_name='profile',
            name='longitude',
            field=models.DecimalField(decimal_places=3, default=25.023, max_digits=8),
        ),
    ]
