# Generated by Django 2.2.7 on 2020-05-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200518_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lattitude',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
        migrations.AlterField(
            model_name='profile',
            name='longitude',
            field=models.DecimalField(decimal_places=3, max_digits=8),
        ),
    ]
