# Generated by Django 2.2.7 on 2020-05-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200520_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='lattitude',
            field=models.DecimalField(decimal_places=3, default=65, max_digits=8),
        ),
        migrations.AlterField(
            model_name='profile',
            name='longitude',
            field=models.DecimalField(decimal_places=3, default=22, max_digits=8),
        ),
    ]
